version: '3.7'
services:
  tempo:
    image: grafana/tempo:main-4d7e191
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./conf/tempo-local.yaml:/etc/tempo.yaml:z
      - ./data/tempo:/tmp/tempo:z
    ports:
      - "14268"

  loki:
    image: grafana/loki:main-f52fc9d
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  prometheus:
    image: prom/prometheus:v2.36.0
    volumes:
      - ./conf/prometheus.yaml:/etc/prometheus/prometheus.yaml:z
      - ./targets.nodes.json:/etc/prometheus/targets.nodes.json:z
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:9.0.0-beta2
    volumes:
      - ./conf/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:z
      - ./conf/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:z
      - ./conf/grafana-localnet.json:/etc/grafana/provisioning/dashboards/localnet.json:z
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
