language: go
go_import_path: github.com/dapperlabs/flow-go

go:
  - 1.12.9
  - 1.13

branches:
  only:
  - master

cache:
  bundler: true
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

script:
  - make ci
