# See https://forum.bors.tech/t/bug-wildcard-status-ignores-1-match/438 
# for why we need to explicitly list all statuses

status = [
  "Lint",
  "Unit Tests (1.16)",
  "Unit Tests (1.17)",
  "Integration Tests (1.16, integration-mvp)",
  "Integration Tests (1.16, integration-ghost)",
  "Integration Tests (1.16, integration-network)",
  "Integration Tests (1.16, integration-epochs)",
  "Integration Tests (1.16, integration-access)",
  "Integration Tests (1.16, integration-collection)",
  "Integration Tests (1.16, integration-consensus)",
  "Integration Tests (1.16, integration-execution)",
  "Integration Tests (1.16, integration-verification)",
  "Integration Tests (1.17, integration-mvp)",
  "Integration Tests (1.17, integration-ghost)",
  "Integration Tests (1.17, integration-network)",
  "Integration Tests (1.17, integration-epochs)",
  "Integration Tests (1.17, integration-access)",
  "Integration Tests (1.17, integration-collection)",
  "Integration Tests (1.17, integration-consensus)",
  "Integration Tests (1.17, integration-execution)",
  "Integration Tests (1.17, integration-verification)",
  "Generate Flaky Test Summary (unit)",
  "Generate Flaky Test Summary (unit-crypto)",
  "Generate Flaky Test Summary (unit-integration)",
  "Generate Flaky Test Summary (integration-mvp)",
  "Generate Flaky Test Summary (integration-ghost)",
  "Generate Flaky Test Summary (integration-network)",
  "Generate Flaky Test Summary (integration-epochs)",
  "Generate Flaky Test Summary (integration-access)",
  "Generate Flaky Test Summary (integration-collection)",
  "Generate Flaky Test Summary (integration-consensus)",
  "Generate Flaky Test Summary (integration-execution)",
  "Generate Flaky Test Summary (integration-verification)",
  "Generate Skipped Test Summary (unit)",
  "Generate Skipped Test Summary (unit-crypto)",
  "Generate Skipped Test Summary (unit-integration)",
  "Generate Skipped Test Summary (integration-mvp)",
  "Generate Skipped Test Summary (integration-ghost)",
  "Generate Skipped Test Summary (integration-network)",
  "Generate Skipped Test Summary (integration-epochs)",
  "Generate Skipped Test Summary (integration-access)",
  "Generate Skipped Test Summary (integration-collection)",
  "Generate Skipped Test Summary (integration-consensus)",
  "Generate Skipped Test Summary (integration-execution)",
  "Generate Skipped Test Summary (integration-verification)",
]

delete_merged_branches = true
required_approvals = 2
