global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          network: localnet
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
        labels:
          network: localnet
  - job_name: node
    static_configs:
      - targets: ["exporter:9100"]
        labels:
          network: localnet
  - job_name: flow
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets.nodes.json"
