name: Flaky Test Monitor

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  push:
    branches:
      - master
  pull_request: # TODO: remove this before merging
    branches:
      - master

env:
  NUM_RUNS: 1
  GCS_BUCKET: production_ddp_flow_test_metrics
  COMMIT_SHA: ${{ github.sha }}
  BIGQUERY_TABLE: dev_src_flow_test_metrics.test_results # TODO: update to production table before merging

jobs:
  level1:
    name: Flaky Test Summary - Level 1
    strategy:
      fail-fast: false
      matrix:
        test-category:
          - unit
          - unit-crypto
          - unit-integration
          - integration-common
          - integration-network
          - integration-epochs
          - integration-access
          - integration-collection
          - integration-consensus
          - integration-execution
          - integration-verification
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run flakiness summary script
      run: ./tools/flaky_test_monitor/flaky-test-monitor-level1.sh
      env:
        TEST_CATEGORY: ${{ matrix.test-category }}