name: Flakiness Summary

on:
  push:
    branches:
      - master

env:
  NUM_RUNS: 1
  GCS_BUCKET: production_ddp_flow_test_metrics
  COMMIT_SHA: ${{ github.sha }}

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run flakiness summary script
      working-directory: ./flakiness_summary
      run: ./flakiness-summary.sh
      env:
        TEST_CATEGORY: unit

  crypto-unit:
    name: Crypto Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run flakiness summary script
      working-directory: ./flakiness_summary
      run: ./flakiness-summary.sh
      env:
        TEST_CATEGORY: crypto-unit

  integration-unit:
    name: Integration Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run flakiness summary script
      working-directory: ./flakiness_summary
      run: ./flakiness-summary.sh
      env:
        TEST_CATEGORY: integration-unit

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run flakiness summary script
      working-directory: ./flakiness_summary
      run: ./flakiness-summary.sh
      env:
        TEST_CATEGORY: integration
  