name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: morphy2k/revive-action@v1.0.1
      with:
        config: revive.toml
        # Only include emulator for now
        path: "./sdk/emulator/..."
      env:
        # GitHub token for annotations
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
