name: Performance CI

on:
  push:
    branches:
      - 'auto-cadence-upgrade/**'
      - staging
      - trying
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - 'auto-cadence-upgrade/**'
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'

env:
  GO_VERSION: 1.19

jobs:
  upload-tps-slices:
    name: Upload TPS Slices
    env:
      TEST_CATEGORY: TPS-Performance
      COMMIT_SHA: ${{ github.sha }}
      RUN_ID: ${{ github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Get job run date
        id: job_run_date
        run: echo "::set-output name=date::$(TZ=":America/Los_Angeles" date -Iseconds)"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_SHA }}
      - name: Get commit date
        id: commit_date
        run: echo "::set-output name=date::$(git show --no-patch --no-notes --pretty='%cI' $COMMIT_SHA)"
      - name: Build relic and other tools
        run: make install-tools
      - name: Run Localnet TPS test
        working-directory: integration/localnet
        run: make tps-test-ci
