name: Skipped Test Tracker

on:
  push:
    branches:
      - master
  pull_request: # TODO: remove this before merging
    branches:
      - master

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }} # TODO: replace with github.sha or $GITHUB_SHA before merging
  RUN_ID: ${{ github.run_id }}
  SKIPPED_TESTS_FILE: skipped-tests
  BIGQUERY_TABLE: dev_src_flow_test_metrics.skipped_tests # TODO: replace with prod before merging

jobs:
  skipped-test-tracker:
    name: Skipped Test Tracker
    strategy:
      fail-fast: false
      matrix:
        test-category:
          - unit
          - unit-crypto
          - unit-integration
          - integration-common
          - integration-network
          - integration-epochs
          - integration-access
          - integration-collection
          - integration-consensus
          - integration-execution
          - integration-verification
    runs-on: ubuntu-latest
    steps:
    - name: Get job run date
      id: date
      run: echo "::set-output name=date::$(TZ=":America/Vancouver" date -Iseconds)"
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ env.COMMIT_SHA }}
    - name: Echo commit sha # TODO: remove before merge
      run: echo $COMMIT_SHA
    - name: Echo commit sha2 # TODO: remove before merge
      run: echo $(git rev-parse HEAD)
    - name: Run skipped test tracker script
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 25
        max_attempts: 10
        command: ./tools/flaky_test_monitor/skipped-test-tracker.sh
      env:
        TEST_CATEGORY: ${{ matrix.test-category }}
        JOB_STARTED: ${{ steps.date.outputs.date }}
    - name: Upload results to BigQuery
      run: bq load --source_format=NEWLINE_DELIMITED_JSON --autodetect $BIGQUERY_TABLE $SKIPPED_TESTS_FILE