name: Skipped Test Tracker

on:
  push:
    branches:
      - master
  pull_request: # TODO: remove this before merging
    branches:
      - master

env:
  COMMIT_SHA: ${{ github.sha }}
  JOB_ID: $(cat /proc/sys/kernel/random/uuid | sed 's/[-]//g' | head -c 20)
  JOB_STARTED: $(TZ=":America/Vancouver" date -Iseconds)

jobs:
  skipped-test-tracker:
    name: Skipped Test Tracker
    strategy:
      fail-fast: false
      matrix:
        test-category:
          - unit
          - unit-crypto
          - unit-integration
          - integration-common
          - integration-network
          - integration-epochs
          - integration-access
          - integration-collection
          - integration-consensus
          - integration-execution
          - integration-verification
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run flakiness summary script
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 25
        max_attempts: 10
        command: ./tools/flaky_test_monitor/skipped-test-tracker.sh
      env:
        TEST_CATEGORY: ${{ matrix.test-category }}